server:
  port: 8010
spring:
  application:
    name: microservice-consume-movie
eureka:
  client:
    service-url:
      defaultZone:  http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true