server:
  port: 8761
eureka:
  client:
    registerWithEureka: false                   #\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230eureka server
    fetchRegistry: false                         #\u662F\u5426\u4ECEeureka server\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/ #\u8BBE\u7F6Eeureka server\u7684\u4EA4\u4E92\u5730\u5740